{"name": "test_x", "status": "broken", "statusDetails": {"message": "AttributeError: 'TestDemo' object has no attribute 'fun_1'", "trace": "self = <pyrunner.test_pytest.TestClass object at 0x10790b130>\n\n    def test_x(self):\n        demo = TestDemo()\n>       demo.fun_1()\nE       AttributeError: 'TestDemo' object has no attribute 'fun_1'\n\npyrunner/test_pytest.py:42: AttributeError"}, "attachments": [{"name": "stdout", "source": "3f54de31-b050-4c5f-8ae9-570448643ab4-attachment.txt", "type": "text/plain"}], "start": 1594572844186, "stop": 1594572844186, "uuid": "27586e31-b82d-4035-9b6a-1de127bc9ca2", "historyId": "45f42406103074b644bdb53f071a6c46", "testCaseId": "7a7a87aef50372aaf17614dc004b54eb", "fullName": "pyrunner.test_pytest.TestClass#test_x", "labels": [{"name": "parentSuite", "value": "pyrunner"}, {"name": "suite", "value": "test_pytest"}, {"name": "subSuite", "value": "TestClass"}, {"name": "host", "value": "192.168.2.101"}, {"name": "thread", "value": "4627-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "pyrunner.test_pytest"}]}