{"name": "test_two", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n +  where False = hasattr('hello', 'hello')", "trace": "self = <pyrunner.test_pytest.TestClass object at 0x1047fe820>\n\n    def test_two(self):\n        x = \"hello\"\n>       assert hasattr(x, \"hello\")\nE       AssertionError: assert False\nE        +  where False = hasattr('hello', 'hello')\n\npyrunner/test_pytest.py:38: AssertionError"}, "attachments": [{"name": "stdout", "source": "f432884c-97aa-4174-b438-ca69790fded7-attachment.txt", "type": "text/plain"}], "start": 1594571907319, "stop": 1594571907319, "uuid": "6c8896a4-30a6-4c14-bbc2-2eb155037ee9", "historyId": "eee204faf163f7e40136f155778226ae", "testCaseId": "3c6259ae3af16af292d5cdd8e763e575", "fullName": "pyrunner.test_pytest.TestClass#test_two", "labels": [{"name": "parentSuite", "value": "pyrunner"}, {"name": "suite", "value": "test_pytest"}, {"name": "subSuite", "value": "TestClass"}, {"name": "host", "value": "192.168.2.101"}, {"name": "thread", "value": "4118-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "pyrunner.test_pytest"}]}