{"name": "test_x", "status": "broken", "statusDetails": {"message": "AttributeError: 'TestDemo' object has no attribute 'fun_1'", "trace": "self = <pyrunner.test_pytest.TestClass object at 0x1047e1460>\n\n    def test_x(self):\n        demo = TestDemo()\n>       demo.fun_1()\nE       AttributeError: 'TestDemo' object has no attribute 'fun_1'\n\npyrunner/test_pytest.py:42: AttributeError"}, "attachments": [{"name": "stdout", "source": "b86c2df2-c88f-4a03-aa2f-1c57b8c5507b-attachment.txt", "type": "text/plain"}], "start": 1594571907331, "stop": 1594571907331, "uuid": "479565ba-0d65-4713-9ec5-6c2a5ccd620b", "historyId": "45f42406103074b644bdb53f071a6c46", "testCaseId": "7a7a87aef50372aaf17614dc004b54eb", "fullName": "pyrunner.test_pytest.TestClass#test_x", "labels": [{"name": "parentSuite", "value": "pyrunner"}, {"name": "suite", "value": "test_pytest"}, {"name": "subSuite", "value": "TestClass"}, {"name": "host", "value": "192.168.2.101"}, {"name": "thread", "value": "4118-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "pyrunner.test_pytest"}]}