<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="0" failures="6" hostname="192.168.2.101" name="pytest" skipped="0" tests="15" time="0.330" timestamp="2020-07-13T00:54:03.981573"><testcase classname="pyrunner.test_div" file="pyrunner/test_div.py" line="5" name="test_div_int" time="0.002"></testcase><testcase classname="pyrunner.test_div" file="pyrunner/test_div.py" line="12" name="test_div_int_param[100-200-0.5]" time="0.002"></testcase><testcase classname="pyrunner.test_div" file="pyrunner/test_div.py" line="12" name="test_div_int_param[10-2-5]" time="0.002"></testcase><testcase classname="pyrunner.test_div" file="pyrunner/test_div.py" line="12" name="test_div_int_param[10-5-2]" time="0.002"></testcase><testcase classname="pyrunner.test_div" file="pyrunner/test_div.py" line="12" name="test_div_int_param[1000000-1-1000000]" time="0.004"></testcase><testcase classname="pyrunner.test_div" file="pyrunner/test_div.py" line="18" name="test_div_float" time="0.001"><failure message="assert 3.3333333333333335 == 3.333333
 +  where 3.3333333333333335 = div(10, 3)">@pytest.mark.happy
    def test_div_float():
&gt;       assert div(10, 3) == 3.333333
E       assert 3.3333333333333335 == 3.333333
E        +  where 3.3333333333333335 = div(10, 3)

pyrunner/test_div.py:21: AssertionError</failure></testcase><testcase classname="pyrunner.test_div" file="pyrunner/test_div.py" line="24" name="test_div_expection" time="0.001"><failure message="TypeError: unsupported operand type(s) for /: &apos;int&apos; and &apos;str&apos;">@pytest.mark.exception
    def test_div_expection():
&gt;       assert div(10, &apos;a&apos;)

pyrunner/test_div.py:27: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

a = 10, b = &apos;a&apos;

    def div(a, b):
        # todu：增加健壮性，异常处理
        #TDD 先写测试用例，再写代码
&gt;       return a/b
E       TypeError: unsupported operand type(s) for /: &apos;int&apos; and &apos;str&apos;

pyrunner/div.py:4: TypeError</failure></testcase><testcase classname="pyrunner.test_div" file="pyrunner/test_div.py" line="30" name="test_div_zero" time="0.001"></testcase><testcase classname="pyrunner.test_pytest" file="pyrunner/test_pytest.py" line="8" name="test_answer" time="0.003"></testcase><testcase classname="pyrunner.test_pytest.TestClass" file="pyrunner/test_pytest.py" line="31" name="test_one" time="0.002"></testcase><testcase classname="pyrunner.test_pytest.TestClass" file="pyrunner/test_pytest.py" line="35" name="test_two" time="0.003"><failure message="AssertionError: assert False
 +  where False = hasattr(&apos;hello&apos;, &apos;hello&apos;)">self = &lt;pyrunner.test_pytest.TestClass object at 0x1078ce7f0&gt;

    def test_two(self):
        x = &quot;hello&quot;
&gt;       assert hasattr(x, &quot;hello&quot;)
E       AssertionError: assert False
E        +  where False = hasattr(&apos;hello&apos;, &apos;hello&apos;)

pyrunner/test_pytest.py:38: AssertionError</failure></testcase><testcase classname="pyrunner.test_pytest.TestClass" file="pyrunner/test_pytest.py" line="39" name="test_x" time="0.002"><failure message="AttributeError: &apos;TestDemo&apos; object has no attribute &apos;fun_1&apos;">self = &lt;pyrunner.test_pytest.TestClass object at 0x10790b130&gt;

    def test_x(self):
        demo = TestDemo()
&gt;       demo.fun_1()
E       AttributeError: &apos;TestDemo&apos; object has no attribute &apos;fun_1&apos;

pyrunner/test_pytest.py:42: AttributeError</failure></testcase><testcase classname="pyrunner.test_pytest.TestClass" file="pyrunner/test_pytest.py" line="43" name="test_zero_division" time="0.003"></testcase><testcase classname="pyrunner.test_pytest.TestDemo" file="unit/test_demo.py" line="38" name="test_demo" time="0.003"><failure message="TypeError: setUp() takes 0 positional arguments but 1 was given">self = &lt;unittest.case._Outcome object at 0x107908130&gt;, test_case = &lt;unit.test_demo.TestDemo testMethod=test_demo&gt;, isTest = False

    @contextlib.contextmanager
    def testPartExecutor(self, test_case, isTest=False):
        old_success = self.success
        self.success = True
        try:
&gt;           yield

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py:60: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py:672: in run
    self._callSetUp()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = &lt;unit.test_demo.TestDemo testMethod=test_demo&gt;

    def _callSetUp(self):
&gt;       self.setUp()
E       TypeError: setUp() takes 0 positional arguments but 1 was given

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py:630: TypeError</failure></testcase><testcase classname="pyrunner.test_pytest.TestDemo" file="unit/test_demo.py" line="30" name="test_sum" time="0.003"><failure message="TypeError: setUp() takes 0 positional arguments but 1 was given">self = &lt;unittest.case._Outcome object at 0x107953fa0&gt;, test_case = &lt;unit.test_demo.TestDemo testMethod=test_sum&gt;, isTest = False

    @contextlib.contextmanager
    def testPartExecutor(self, test_case, isTest=False):
        old_success = self.success
        self.success = True
        try:
&gt;           yield

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py:60: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py:672: in run
    self._callSetUp()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = &lt;unit.test_demo.TestDemo testMethod=test_sum&gt;

    def _callSetUp(self):
&gt;       self.setUp()
E       TypeError: setUp() takes 0 positional arguments but 1 was given

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py:630: TypeError</failure></testcase></testsuite></testsuites>